Feature/functions
pagopa/pn-infra-confinfo pull request #16
Opened 2024-02-06 15:59 UTC by Vallasc

2024-02-07 21:03 UTC, fdammassa requested changes
Ti ho chiesto delle piccole modifiche

2024-02-07 21:03 UTC, fdammassa commented on src/main/modules/diagnostic-data-proxy/main.tf
> +        Resource = "arn:aws:dynamodb:${var.aws_region}:${var.pn_confinfo_aws_account_id}:*"
@Vallasc esplicitiamo le tabelle

2024-02-09 14:10 UTC, Vallasc commented on src/main/modules/diagnostic-data-proxy/main.tf
> +  source_code_hash = (var.filename != null ? filebase64sha256(var.filename) : sha256(var.s3_code_key))
Calcolerebbe lo SHA-256 della chiave dell'oggetto S3; se la chiave è formata da `{commit_id}/function.zip` allora Terraform ricaricherebbe il codice ad ogni giro della pipeline.

2024-02-15 16:20 UTC, fdammassa approved these changes

2024-02-22 13:32 UTC, merged