Added SES to endpoints list
pagopa/pn-infra-confinfo pull request #6
Opened 2023-05-12 13:29 UTC by fdammassa

2023-05-12 13:31 UTC, MTurraPpa approved these changes

2023-05-12 13:31 UTC, MTurraPpa requested changes
Error: No release type found in pull request title "Added SES to endpoints list". Add a prefix to indicate what kind of release this pull request corresponds to. For reference, see https://www.conventionalcommits.org/

2023-05-15 06:35 UTC, MTurraPpa approved these changes

2023-05-16 16:12 UTC, marco-vit-pagopa approved these changes

2023-05-16 16:14 UTC, merged